### ISSUE TITLE
Potential blind spot?

### ISSUE THREAD

**Issue by isabelroses** [jakehamilton/nixpkgs.news#4]
I'm not sure if the missing PR was intentionally left out or there is a blindspot with your github PR fetching script.

Mentioned PRs
- 2024-04-21 - [303817](https://github.com/NixOS/nixpkgs/pull/303817) - adds fork-cleaner
- 2024-04-14 - [303997](https://github.com/NixOS/nixpkgs/pull/303997) - adds pace

Missing PRs
- [303823](https://github.com/NixOS/nixpkgs/pull/303823) - adds kittysay

**Comment by jakehamilton** [comment]
Hmm yeah that seems like it should have been included. If the PR was merged between Sunday and Saturday of last week then the script should have fetched it. I have had issues with the GitHub API, I wonder if there is something strange going on or if my logic is incomplete...

I'll add a mention for the package, thank you!

**Comment by jakehamilton** [comment]
I've updated the latest issue to include `kittysay` (thanks again); I'm going to close this issue for now, but I'm fairly convinced that my script isn't fetching _all_ of the merged PRs from the previous week. If this happens again then maybe I can try looking into it, otherwise it's possible that this is a fluke.
